import sys, os
import re
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../')))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../src')))
from src.agent.affiliate_promoter import YouTubeAPIClient, AliExpressAPIClient
from slideshow_maker import download_images, make_slideshow
from tts_helper import generate_tts_audio

print("[DEBUG] Ξεκινάει το AliExpress -> Slideshow -> YouTube demo!")

# 1. Discover product from AliExpress
aliexpress_client = AliExpressAPIClient()
products = aliexpress_client.search_products(query="smartwatch", limit=1)
print(f"[DEBUG] Βρέθηκαν {len(products)} προϊόντα από AliExpress.")
if not products:
    print("No products found!")
    exit(1)
product = products[0]
print(f"[DEBUG] Τίτλος προϊόντος: {product.title}")

# 2. Get image URLs (main + small images if available)
image_urls = []
if hasattr(product, 'image') and product.image:
    image_urls.append(product.image)
if hasattr(product, 'product_small_image_urls') and product.product_small_image_urls:
    image_urls.extend(product.product_small_image_urls)
image_urls = list(set(image_urls))  # remove duplicates
print(f"[DEBUG] Βρέθηκαν {len(image_urls)} εικόνες προϊόντος.")

# 3. Generate script (simple demo)
script = f"""
[Male Voice]
Welcome to SuggestoAI! Today, we're reviewing the {product.title}.
This watch features amazing specs and is perfect for everyday use.
[Disclosure]
[Male Voice] This video contains affiliate links. Content generated by AI.
[Call-to-Action]
[Male Voice] Check the link in the description to get yours now!
[Outro]
[Male Voice] SuggestoAI – Your smart product finder!
"""

print("[DEBUG] Κατεβάζω εικόνες προϊόντος...")
imgs = download_images(image_urls)
print(f"[DEBUG] Αποθηκεύτηκαν {len(imgs)} εικόνες: {imgs}")
print("[DEBUG] Παράγω TTS audio...")
audio_path = generate_tts_audio(script, output_audio="output_tts.mp3")
print(f"[DEBUG] Audio path: {audio_path}")
print("[DEBUG] Φτιάχνω slideshow video...")
video_path = make_slideshow(imgs, audio_path=audio_path, output_path="final_video.mp4")
print(f"[DEBUG] Video path: {video_path}")
print("[DEBUG] Ανεβάζω στο YouTube...")
title = "SuggestoAI Product Review"
print(f"[DEBUG] Τελικός τίτλος για YouTube: '{title}'")
youtube_client = YouTubeAPIClient()
try:
    response = youtube_client.upload_video(
        video_file=video_path,
        title=title,
        description=f"Affiliate link: {product.affiliate_link}\nThis is a fully automated affiliate video generated by SuggestoAI agent.",
        tags=["affiliate", "suggestoai", "ai-generated", "review"],
        privacy_status="unlisted"
    )
except Exception as e:
    print(f"[DEBUG] Exception on upload: {e}.")
    response = None
print("[DEBUG] Upload response:", response) 