import os
from agent.scripts.slideshow_maker import download_images, make_slideshow
from agent.scripts.tts_helper import generate_tts_audio
from agent.affiliate_promoter import YouTubeAPIClient

# Example product data (θα το παίρνεις από το AliExpress API)
product = {
    "title": "2025 New Watch 7 Ultra Smart Watch",
    "image_urls": [
        "https://ae-pic-a1.aliexpress-media.com/kf/Se51bf07b1d564b89b0149f61060f9d20W.jpg",
        "https://ae-pic-a1.aliexpress-media.com/kf/Sab9ab2ac52194d28b77ec4b036a71b430.jpg",
        "https://ae-pic-a1.aliexpress-media.com/kf/Sc18cb7f55aff4778914f39a0d5d8db09v.jpg"
    ],
    "script": """
[Male Voice]
Welcome to SuggestoAI! Today, we're reviewing the brand new 2025 New Watch 7 Ultra Smart Watch – the ultimate smartwatch for 2025!
This watch features 32GB memory, GPS, NFC, waterproof design, and advanced health tracking. It's stylish and perfect for both sports and everyday use.
[Q&A Dialogue]
[Female Voice] Is it compatible with both Android and iOS?
[Male Voice] Absolutely! It works seamlessly with both Android and iOS devices.
[Female Voice] How long does the battery last?
[Male Voice] You get up to 7 days of battery life on a single charge, even with all features enabled!
[Disclosure]
[Male Voice] This video contains affiliate links. Content generated by AI.
[Call-to-Action]
[Male Voice] Check the link in the description to get yours now and enjoy exclusive discounts! Don't forget to subscribe for more smart product reviews from SuggestoAI!
[Outro]
[Male Voice] SuggestoAI – Your smart product finder!
"""
}

def integrated_affiliate_video(product):
    print("Downloading product images...")
    imgs = download_images(product["image_urls"])
    print("Generating TTS audio...")
    audio_path = generate_tts_audio(product["script"], output_audio="output_tts.mp3")
    print("Making slideshow video...")
    video_path = make_slideshow(imgs, audio_path=audio_path, output_path="final_video.mp4")
    print("Uploading to YouTube...")
    youtube_client = YouTubeAPIClient()
    response = youtube_client.upload_video(
        video_file=video_path,
        title=f"{product['title']} | SuggestoAI Review",
        description="This is a fully automated affiliate video generated by SuggestoAI agent.",
        tags=["affiliate", "suggestoai", "ai-generated", "review"],
        privacy_status="unlisted"
    )
    print("Upload response:", response)
    return response

if __name__ == "__main__":
    integrated_affiliate_video(product) 