import sys
import os
src_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../src'))
sys.path.insert(0, src_dir)

from agent.affiliate_promoter import YouTubeAPIClient

# Εκτέλεσε αυτό το script από τον root φάκελο με:
# PYTHONPATH=. python3 agent/scripts/api_tests/test_youtube_upload.py
# Αν λείπει το google-api-python-client, εγκατέστησέ το με:
# pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

youtube_client = YouTubeAPIClient()

# Path στο τελικό βίντεο που παράχθηκε από το video composer
video_file = "final_video.mp4"

title = "SuggestoAI Affiliate Video Demo"
description = "This is a fully automated affiliate video generated by SuggestoAI agent."
tags = ["affiliate", "suggestoai", "ai-generated", "review"]

response = youtube_client.upload_video(
    video_file=video_file,
    title=title,
    description=description,
    tags=tags,
    privacy_status="unlisted"
)
print("Upload response:", response) 